### ISSUE TITLE
Sometimes c.GetHashCode() returns negative integer, thus composing invalid Haskell identifier

### ISSUE THREAD

**Issue by SnowOnion** [kazakami/Hasukeru#1]
I tried the example in Readme:
```
階阿定畳乗壱[壱至阿]
主推穢空
主定行
　曰、示、階六
```
and I get
```
var-1769040242 a = foldr (*) 1 [1 .. a ]
main :: IO () 
main = do 
 putStrLn $ show $ var-1769040242 6 
```
.
Obviously the code at https://github.com/kazakami/Hasukeru/blob/master/kanji.cs line131:
`        return "var" + c.GetHashCode() + " ";`
converted `階` to `-1769040242`.

Have you encountered such case that `GetHashCode()` returns negative integer?

My environment:
Windows 10 (Chinese. Does it matter?),
.NET Framework 4.5

p.s.
私は日本語とHaskellを初めに勉強しました。面白いrepo！:)

**Comment by kazakami** [comment]
Fixed a problem when `GetHashCode()` return negative integer with the latest commit.
